### ISSUE TITLE
Inferrability failure

### ISSUE THREAD

**Issue by timholy** [vtjnash/ComputedFieldTypes.jl#2]
```julia
julia> using ComputedFieldTypes

julia> @computed type Mine{N}
           x::NTuple{N,Int}
           y::NTuple{2^N,Int}

           function Mine{N}(x::NTuple{N,Int}) where N
               y = ntuple(identity, Val{2^N})
               new(x, y)
           end
       end

julia> @code_warntype Mine{2}((1,2))
Variables:
  #self#::Any
  x::Tuple{Int64,Int64}
  y::Any

Body:
  begin 
      y::Any = (Main.ntuple)(Main.identity, (Core.apply_type)(Main.Val, $(Expr(:invoke, MethodInstance for power_by_squaring(::Int64, ::Int64), :(Base.power_by_squaring), 2, :($(Expr(:static_parameter, 1))))))::Type{Val{_}} where _)::Any # line 7:
      SSAValue(0) = (Core.apply_type)(Main.Mine, $(Expr(:static_parameter, 1)), $(Expr(:invoke, MethodInstance for power_by_squaring(::Int64, ::Int64), :(Base.power_by_squaring), 2, :($(Expr(:static_parameter, 1))))))::Type{Mine{2,_}} where _
      return $(Expr(:new, SSAValue(0), :((Base.convert)((Core.fieldtype)(SSAValue(0), :x)::Type{#s45} where #s45<:Tuple{Int64,Int64}, x)::Tuple), :((Base.convert)((Core.fieldtype)(SSAValue(0), :y)::Type{#s45} where #s45<:(Tuple{Vararg{Int64,_}} where _), y))))
  end::Mine{2,_} where _
```
It's not helped if one changes the `ntuple` call to `ntuple(identity, 2^N)`.

**Comment by timholy** [comment]
Hmm, `fulltype` is also not inferrable:
```julia
julia> @code_warntype fulltype(Mine{3})
Variables:
  #self#::ComputedFieldTypes.#fulltype
  #unused#::Any

Body:
  begin 
      return (Core.apply_type)(Main.Mine, $(Expr(:static_parameter, 1)), $(Expr(:invoke, MethodInstance for power_by_squaring(::Int64, ::Int64), :(Base.power_by_squaring), 2, :($(Expr(:static_parameter, 1))))))::Type{Mine{3,_}} where _
  end::Type{Mine{3,_}} where _
```

A potential [workaround](https://github.com/JuliaLang/julia/issues/22513#issuecomment-313445710) is OK for now but may not in the future.

**Comment by vtjnash** [comment]
It's going to be difficult to teach inference that `^` is computable. Anyways, the purpose of this package is not to make uninferrable things magically computed. The purpose of this package is simply to demonstrate how https://github.com/JuliaLang/julia/issues/18466 would look and behave if implemented in base.

**Comment by timholy** [comment]
Got it, I imagined there was more `@pure` magic going on...but it doesn't seem like there is.

**Comment by vtjnash** [comment]
It seems like it is going to be difficult to teach inference that `^` is pure. The closest I can suggest right now is to use `Base.@pure pure_pow(x, y) = x^y`.

This package is only intended as a demonstration of what JuliaLang/julia#18466 would look like if implemented in Base. It's not intended as a mechanism to make uninferrable functions magically computable. (which is pretty much the same discussion as happened with https://github.com/mauro3/SimpleTraits.jl/pull/39, if you wish to revisit the issue)
