### ISSUE TITLE
Computing type parameter problem

### ISSUE THREAD

**Issue by chakravala** [vtjnash/ComputedFieldTypes.jl#8]
Consider the following example:
```Julia
using SparseArrays, ComputedFieldTypes
@computed struct CFT{N}
    v::SVector{2^N,Int}
end
```
It would be great if the following type could be fully computed:
```Julia
julia> CFT{1}
CFT{1,328} where 328
```
However, instead of `CFT{1,2}` we get `CFT{1,X} where X`.

Is there any way to fix this?

**Comment by vtjnash** [comment]
If we filled in that parameter earlier, then it wouldn't be a computed-type-parameter anymore, defeating the point and design of the package

**Comment by chakravala** [comment]
What I'm pointing out in this issue is more of an issue with the Julia language itself. It would be good if there were a way for Julia to know that the second parameter always depends on the first parameter. This wouldn't make this package obsolete, it would just make it more convenient to use. I think the Julia language itself would have to be updated so that it would be possible to specify that one parameter depends on the other to automatically fill in the `where` statement in a parametric dependence situation.

Don't think you really understood what I'm trying to say in this issue, but anyways it probably would need to be a fix in the base language and not in a package.
